### ISSUE TITLE
Change search preferences

### ISSUE THREAD

**Issue by cloudybyte** [Kaktushose/tinder-api-docs#13]
**route:** 
`/profile`

**method:**
`POST`

**request body:**
`{"age_filter_min": age_filter_min, "gender_filter": gender_filter, "gender": gender, "age_filter_max": age_filter_max, "distance_filter": distance_filter}`

**Comment by Kaktushose** [comment]
v2 route is `/v2/profile` 

**request body:** 
```json
{
    "user": {
        "age_filter_min": age_filter_min,
        "gender_filter": gender_filter,
        "gender": gender,
        "age_filter_max": age_filter_max,
        "distance_filter": distance_filter
    }
}
```
